apiVersion: v1
kind: ServiceAccount
metadata:
  name: flagger-slack-handler-sa
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flagger-slack-handler-cluster-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flagger-slack-handler-cluster-rolebinding
subjects:
- kind: ServiceAccount
  name: flagger-slack-handler-sa
  namespace: ci
roleRef:
  kind: ClusterRole
  name: flagger-slack-handler-cluster-role
  apiGroup: rbac.authorization.k8s.io