apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flagger-slack-handler
  name: flagger-slack-handler
spec:
  minReadySeconds: 5
  progressDeadlineSeconds: 60
  selector:
    matchLabels:
      app: flagger-slack-handler
  template:
    metadata:
      labels:
        app: flagger-slack-handler
    spec:
      containers:
      - args:
        - -loadtester-namespace=ci
        image: mayankshah1607/flagger-slack-handler
        imagePullPolicy: IfNotPresent
        name: flagger-slack-handler
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 2000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 64Mi