apiVersion: v1
kind: Service
metadata:
  name: flagger-slack-handler
spec:
  type: ClusterIP
  selector:
    app: flagger-slack-handler
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
